steps:
- task: NodeTool@0
  inputs:
    versionSpec: "8.x"
  displayName: Install node 8
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webApp'
    WebAppName: 
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# install dependencies
- script: npm install
  displayName: npm install

# build
- script: npm run build
  displayName: npm run build

- script: npm run units
  displayName: Run unit tests
