# Shared template for build and test steps
parameters:
- name: nodeVersions
  type: object
  default:
    'Node 16':
      versionSpec: '16.x'
      npmVersion: '8'
    'Node 18':
      versionSpec: '18.x'
      npmVersion: '10'
    'Node 20':
      versionSpec: '20.x'
      npmVersion: '10'
    'Node 22':
      versionSpec: '22.x'
      npmVersion: '10'

jobs:
- job: BuildAndTest
  displayName: Build and Test
  strategy:
    matrix: ${{ parameters.nodeVersions }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(versionSpec)
    displayName: Install node
  - script: npm install -g npm@$(npmVersion)
    displayName: Upgrade npm
  - task: NpmAuthenticate@0
    inputs:
      workingFile: .npmrc
  - script: npm install
    displayName: npm install
  - script: npm run build
    displayName: npm run build
  - script: npm run units
    displayName: Run unit tests
